spring:
  application:
    name: herbal-impression

  datasource:
    url: jdbc:mysql://localhost:3306/herbal
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
